@extends('layouts.app')

@section('title', 'Activity Calendar')

@section('content')
<div class="container mx-auto px-4 py-8">
    <div class="flex justify-between items-center mb-8">
        <h1 class="text-3xl font-bold text-gray-900">Activity Calendar</h1>
        <div class="flex space-x-4">
            <a href="{{ route('activities.index') }}" 
               class="text-gray-600 hover:text-gray-800">
                List View
            </a>
            @if(auth()->check())
                <a href="{{ route('activities.create') }}" 
                   class="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg transition duration-200">
                    Create Activity
                </a>
            @endif
        </div>
    </div>

    <!-- Calendar Filters -->
    <div class="bg-white rounded-lg shadow-md p-6 mb-8">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">Month</label>
                <select id="month-filter" class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500">
                    @for($month = 1; $month <= 12; $month++)
                        <option value="{{ $month }}" {{ date('n') == $month ? 'selected' : '' }}>
                            {{ date('F', mktime(0, 0, 0, $month, 1)) }}
                        </option>
                    @endfor
                </select>
            </div>
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">Year</label>
                <select id="year-filter" class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500">
                    @for($year = date('Y') - 2; $year <= date('Y') + 2; $year++)
                        <option value="{{ $year }}" {{ date('Y') == $year ? 'selected' : '' }}>
                            {{ $year }}
                        </option>
                    @endfor
                </select>
            </div>
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-2">Organization</label>
                <select id="org-filter" class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500">
                    <option value="">All Organizations</option>
                    @foreach(\App\Models\Organization::orderBy('name')->get() as $org)
                        <option value="{{ $org->id }}">{{ $org->name }}</option>
                    @endforeach
                </select>
            </div>
        </div>
    </div>

    <!-- Calendar Grid -->
    <div class="bg-white rounded-lg shadow-md p-6 mb-8">
        <div class="grid grid-cols-7 gap-px bg-gray-200">
            <!-- Day Headers -->
            <div class="bg-gray-50 p-3 text-center font-semibold text-gray-700">Sun</div>
            <div class="bg-gray-50 p-3 text-center font-semibold text-gray-700">Mon</div>
            <div class="bg-gray-50 p-3 text-center font-semibold text-gray-700">Tue</div>
            <div class="bg-gray-50 p-3 text-center font-semibold text-gray-700">Wed</div>
            <div class="bg-gray-50 p-3 text-center font-semibold text-gray-700">Thu</div>
            <div class="bg-gray-50 p-3 text-center font-semibold text-gray-700">Fri</div>
            <div class="bg-gray-50 p-3 text-center font-semibold text-gray-700">Sat</div>
        </div>
        
        <div id="calendar-grid" class="grid grid-cols-7 gap-px bg-gray-200">
            <!-- Calendar days will be generated by JavaScript -->
        </div>
    </div>

    <!-- Upcoming Activities -->
    <div class="bg-white rounded-lg shadow-md p-6">
        <h2 class="text-xl font-semibold text-gray-900 mb-4">Upcoming Activities</h2>
        <div id="upcoming-activities" class="space-y-4">
            @foreach($activities->where('start_date', '>', now())->take(5) as $activity)
                <div class="flex items-start space-x-4 p-4 border border-gray-200 rounded-lg hover:bg-gray-50">
                    <div class="flex-shrink-0">
                        <div class="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
                            <span class="text-blue-600 font-bold">{{ $activity->start_date->format('j') }}</span>
                        </div>
                    </div>
                    <div class="flex-1">
                        <h3 class="font-medium text-gray-900">{{ $activity->title }}</h3>
                        <p class="text-sm text-gray-600">{{ $activity->organization->name }}</p>
                        <div class="flex items-center mt-1 text-sm text-gray-500">
                            <svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                            </svg>
                            {{ $activity->start_date->format('M j, Y - g:i A') }}
                        </div>
                        <div class="flex items-center mt-1 text-sm text-gray-500">
                            <svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"></path>
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"></path>
                            </svg>
                            {{ $activity->location }}
                        </div>
                    </div>
                    <div class="flex-shrink-0">
                        <a href="{{ route('activities.show', $activity) }}" 
                           class="text-blue-600 hover:text-blue-800 text-sm font-medium">
                            View Details
                        </a>
                    </div>
                </div>
            @endforeach
        </div>
        
        @if($activities->where('start_date', '>', now())->count() == 0)
            <div class="text-center py-8">
                <svg class="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                </svg>
                <h3 class="mt-2 text-sm font-medium text-gray-900">No upcoming activities</h3>
                <p class="mt-1 text-sm text-gray-500">Check back later for new events.</p>
            </div>
        @endif
    </div>
</div>

<script>
// Activities data from server
const activities = @json($activities);

function generateCalendar(month, year, organizationId = null) {
    const firstDay = new Date(year, month - 1, 1);
    const lastDay = new Date(year, month, 0);
    const startDate = new Date(firstDay);
    startDate.setDate(startDate.getDate() - firstDay.getDay());
    
    const calendarGrid = document.getElementById('calendar-grid');
    calendarGrid.innerHTML = '';
    
    const endDate = new Date(lastDay);
    endDate.setDate(endDate.getDate() + (6 - lastDay.getDay()));
    
    const currentMonth = month - 1;
    
    for (let date = new Date(startDate); date <= endDate; date.setDate(date.getDate() + 1)) {
        const dateStr = date.toISOString().split('T')[0];
        const isCurrentMonth = date.getMonth() === currentMonth;
        const isToday = date.toDateString() === new Date().toDateString();
        
        const dayElement = document.createElement('div');
        dayElement.className = `bg-white p-2 min-h-24 ${!isCurrentMonth ? 'bg-gray-50 text-gray-400' : ''} ${isToday ? 'bg-blue-50' : ''}`;
        
        // Day number
        const dayNumber = document.createElement('div');
        dayNumber.className = `font-medium mb-1 ${isToday ? 'text-blue-600' : ''}`;
        dayNumber.textContent = date.getDate();
        dayElement.appendChild(dayNumber);
        
        // Activities for this day
        const dayActivities = activities.filter(activity => {
            const activityDate = new Date(activity.start_date).toISOString().split('T')[0];
            const matchesDate = activityDate === dateStr;
            const matchesOrg = !organizationId || activity.organization_id == organizationId;
            return matchesDate && matchesOrg && activity.status === 'published';
        });
        
        dayActivities.forEach(activity => {
            const activityElement = document.createElement('div');
            activityElement.className = 'text-xs p-1 mb-1 bg-blue-100 text-blue-800 rounded truncate cursor-pointer hover:bg-blue-200';
            activityElement.textContent = activity.title;
            activityElement.title = activity.title;
            activityElement.onclick = () => {
                window.location.href = `/activities/${activity.id}`;
            };
            dayElement.appendChild(activityElement);
        });
        
        calendarGrid.appendChild(dayElement);
    }
}

// Initialize calendar
document.addEventListener('DOMContentLoaded', function() {
    const monthFilter = document.getElementById('month-filter');
    const yearFilter = document.getElementById('year-filter');
    const orgFilter = document.getElementById('org-filter');
    
    function updateCalendar() {
        const month = parseInt(monthFilter.value);
        const year = parseInt(yearFilter.value);
        const organizationId = orgFilter.value;
        generateCalendar(month, year, organizationId);
    }
    
    monthFilter.addEventListener('change', updateCalendar);
    yearFilter.addEventListener('change', updateCalendar);
    orgFilter.addEventListener('change', updateCalendar);
    
    // Generate initial calendar
    updateCalendar();
});
</script>
@endsection